### Variables
@base = https://chat.abharya.ir/v1
@auth-token-1 = 411ec0ad2cf0e9d4f73277a3ecebc92faaa98694
@auth-token-2 = f709b51115079dc8f77a53b3852c568729391c82
@chat_session = 6ae942f1-c9c1-4257-9b3b-0e4bde4ebf31
@contentType = application/json
###
# Register new user
POST {{base}}/auth/users/
Content-Type: {{contentType}}

{    
    "username":"",
    "password": ""
}

###
# Get auth token
POST {{base}}/auth/token/login/
Content-Type: {{contentType}}

{    
    "username":"fatemeh",
    "password": "fa331080"
}

###
# Create new chat session
POST {{base}}/chats/
Authorization: Token {{auth-token-1}}
Content-Type: {{contentType}}

{
    "session_name": "تست"
}

###
# Get all chat sessions that the user chats in
GET {{base}}/chats/
Authorization: Token {{auth-token-2}}
Content-Type: {{contentType}}
###
# Register user as a member of the chat sessions
POST {{base}}/chats/{{chat_session}}/members/
Authorization: Token {{auth-token-2}}
Content-Type: {{contentType}}
###
# Get detail of a chat sessions that user owns
GET {{base}}/chats/{{chat_session}}/
Authorization: Token {{auth-token-1}}
Content-Type: {{contentType}}
###
# Post a chat message
POST {{base}}/chats/{{chat_session}}/messages/
Authorization: Token {{auth-token-1}}
Content-Type: {{contentType}}

{
     "message": "salam"
}
###
# Get messages of a chat session
GET {{base}}/chats/{{chat_session}}/messages/
Authorization: Token {{auth-token-1}}
Content-Type: {{contentType}}
###
# Get details of chat message from a session
GET  {{base}}/chats/{{chat_session}}/messages/3
Authorization: Token {{auth-token-1}}
Content-Type: {{contentType}}
###
# Delete a chat message from a session
DELETE {{base}}/chats/{{chat_session}}/messages/22
Authorization: Token {{auth-token-1}}
Content-Type: {{contentType}}
###