# Generated by Django 4.2a1 on 2023-01-17 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Chats",
            new_name="Chat",
        ),
        migrations.RenameModel(
            old_name="Emotes",
            new_name="Emote",
        ),
        migrations.AlterModelOptions(
            name="chat",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="emote",
            options={"ordering": ["code"]},
        ),
    ]
