# Generated by Django 4.1.5 on 2023-01-17 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_chats_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chats",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="emotes",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
