# Generated by Django 4.1.5 on 2023-01-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_chats_date_alter_emotes_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chats",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="emotes",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
